[workspace]
name = "json-kern"
members = [
    "json",
    "json-test",
    "json-bench",
]

[workspace.exports]
json = { member = "json" }

[workspace.package]
version = "0.1.0"
kern = "0.7.5"
license = "MIT"
authors = ["softfault <givenyoung46@gmail.com>"]
readme = "README.md"
repository = "https://github.com/softfault/json-kern.git"

[workspace.dependencies]
json = { path = "json" }
