[package]
name = "json-test"
publish = false
description = "Extended conformance tests for json-kern"

[[bin]]
name = "json-test"
root = "src/main.kn"

[dependencies]
json = { workspace = true }

[resources]
JSONTestSuite = { git = "https://github.com/nst/JSONTestSuite.git", rev = "1ef36fa01286573e846ac449e8683f8833c5b26a" }
